//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.kr {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PublicCoin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicCoin() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.kr.PublicCoin", typeof(PublicCoin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   마켓명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChanceMarketName {
            get {
                return ResourceManager.GetString("ChanceMarketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChanceOrderBtnCancel {
            get {
                return ResourceManager.GetString("ChanceOrderBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미체결량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChanceOrderNotConclusion {
            get {
                return ResourceManager.GetString("ChanceOrderNotConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문가격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChanceOrderPrice {
            get {
                return ResourceManager.GetString("ChanceOrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChanceOrderQuantity {
            get {
                return ResourceManager.GetString("ChanceOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CoinBuy {
            get {
                return ResourceManager.GetString("CoinBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   코인명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CoinName {
            get {
                return ResourceManager.GetString("CoinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CoinSell {
            get {
                return ResourceManager.GetString("CoinSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   체결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화폐과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수수료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지정가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시장가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소주문금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MinOrderPrice {
            get {
                return ResourceManager.GetString("MinOrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   월과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미체결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotConclusion {
            get {
                return ResourceManager.GetString("NotConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문내역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문가능과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등락율과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
